apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-master-deployment
  namespace: kubernetes-cluster-shivam
  labels:
    app: nagp-master
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp-master
  template:
    metadata:
      labels:
        app: nagp-master
    spec:
      containers:
      - name: nagp-master
        image: shivamgupta04/samplewebapi:latest
        ports:
          - name: http
            containerPort: 80
            protocol: TCP

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: nagp-deployment-service-master
  namespace: kubernetes-cluster-shivam
  labels:
    app: nagp-master
spec:
  type: NodePort
  selector: 
    app: nagp-master
  ports: 
  - protocol: "TCP"
    nodePort: 30157
    port: 80
    targetPort: 80
  selector: 
    app: nagp-master
  type: "LoadBalancer"
