apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-develop-deployment
  namespace: kubernetes-cluster-shivam
  labels:
    app: nagp-develop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp-develop
  template:
    metadata:
      labels:
        app: nagp-develop
    spec:
      containers:
      - name: nagp-develop
        image: shivamgupta04/samplewebapi:latest
        ports:
          - name: http
            containerPort: 80
            protocol: TCP

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: nagp-deployment-service-develop
  namespace: kubernetes-cluster-shivam
  labels:
    app: nagp-develop
spec:
  type: NodePort
  selector: 
    app: nagp-develop
  ports: 
  - protocol: "TCP"
    nodePort: 30158
    port: 80
    targetPort: 80
  selector: 
    app: nagp-develop
  type: "LoadBalancer"
